version: "3"
services:
 vite_frontend:
   image: node:alpine
   platform: linux/amd64 # M1/2 Chip fix
   container_name: stock_frontend
   entrypoint: /bin/sh
   ports:
     - 8000:8000
   working_dir: /srv/app
   volumes:
     - type: bind
       source: ./
       target: /srv/app
   tty: true